# Generated by Django 4.2.11 on 2024-05-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendor_pulse", "0002_alter_historicalperformance_vendor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperformance",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="average_response_time",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="fulfillment_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="on_time_delivery_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="quality_rating_avg",
            field=models.FloatField(default=0.0),
        ),
    ]
